In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data={"Car_ID":list(range(1001,1051)),
"Brand":["Toyota", "Honda", "Hyundai", "Maruti", "Tata",
        "Toyota", "Honda", "Hyundai", "Ford", "Kia",
        "Tata", "Toyota", "Honda", "Maruti", "Hyundai",
        "Kia", "Ford", "Toyota", "Tata", "Honda",
        "Hyundai", "Maruti", "Kia", "Toyota", "Ford",
        "Honda", "Tata", "Hyundai", "Toyota", "Maruti",
        "Kia", "Honda", "Ford", "Tata", "Toyota",
        "Hyundai", "Maruti", "Honda", "Kia", "Toyota",
        "Ford", "Tata", "Hyundai", "Honda", "Maruti",
        "Toyota", "Kia", "Ford", "Tata", "Honda"],
"Model":["Camry", "Civic", "Creta", "Swift", "Nexon",
        "Corolla", "City", "i20", "EcoSport", "Seltos",
        "Harrier", "Fortuner", "Amaze", "Baleno", "Venue",
        "Sonet", "Endeavour", "Innova", "Nexon", "City",
        "Verna", "Swift", "Carens", "Corolla", "Aspire",
        "Civic", "Punch", "Creta", "Camry", "Baleno",
        "Seltos", "Amaze", "EcoSport", "Harrier", "Fortuner",
        "i20", "Swift", "City", "Sonet", "Innova",
        "Endeavour", "Nexon", "Verna", "Civic", "Baleno",
        "Camry", "Carens", "Aspire", "Punch", "Amaze"],
"Year":[2020, 2019, 2021, 2018, 2022,
        2020, 2019, 2021, 2018, 2022,
        2020, 2021, 2019, 2022, 2020,
        2021, 2018, 2022, 2020, 2019,
        2021, 2018, 2022, 2020, 2019,
        2021, 2022, 2020, 2019, 2021,
        2022, 2018, 2020, 2021, 2019,
        2022, 2020, 2018, 2021, 2022,
        2019, 2020, 2021, 2018, 2022,
        2020, 2019, 2021, 2022, 2018],
"Price":[25000, 22000, 24000, 12000, 18000,
        27000, 21000, 16000, 15000, 23000,
        28000, 42000, 17000, 14000, 19000,
        21000, 35000, 30000, 20000, 19000,
        18000, 11000, 25000, 26000, 13000,
        23000, 10000, 22000, 29000, 15000,
        24000, 16000, 14000, 27000, 40000,
        17000, 12500, 20000, 21500, 31000,
        33000, 19000, 17500, 22500, 13500,
        30000, 24500, 14500, 15500, 18500],
"Mileage":[45000, 52000, 30000, 60000, 25000,
        40000, 48000, 35000, 70000, 28000,
        32000, 45000, 50000, 22000, 38000,
        29000, 65000, 41000, 33000, 55000,
        27000, 62000, 24000, 36000, 68000,
        42000, 31000, 39000, 28000, 46000,
        26000, 53000, 72000, 34000, 44000,
        37000, 58000, 49000, 23000, 35000,
        61000, 30000, 32000, 47000, 54000,
        29000, 25000, 66000, 43000, 51000],
"Fuel_Type":["Petrol", "Diesel", "Petrol", "Petrol", "Diesel",
        "Petrol", "Diesel", "Petrol", "Diesel", "Petrol",
        "Diesel", "Diesel", "Petrol", "Petrol", "Diesel",
        "Petrol", "Diesel", "Diesel", "Petrol", "Diesel",
        "Petrol", "Petrol", "Petrol", "Diesel", "Petrol",
        "Petrol", "Petrol", "Diesel", "Petrol", "Petrol",
        "Diesel", "Petrol", "Diesel", "Diesel", "Petrol",
        "Petrol", "Diesel", "Petrol", "Petrol", "Diesel",
        "Diesel", "Petrol", "Petrol", "Diesel", "Petrol",
        "Diesel", "Petrol", "Diesel", "Petrol", "Petrol"],
"Transmission":[ "Automatic", "Manual", "Automatic", "Manual", "Manual",
        "Automatic", "Manual", "Manual", "Manual", "Automatic",
        "Automatic", "Automatic", "Manual", "Manual", "Automatic",
        "Automatic", "Manual", "Automatic", "Manual", "Manual",
        "Automatic", "Manual", "Automatic", "Automatic", "Manual",
        "Automatic", "Manual", "Automatic", "Automatic", "Manual",
        "Automatic", "Manual", "Manual", "Automatic", "Automatic",
        "Manual", "Manual", "Automatic", "Manual", "Automatic",
        "Automatic", "Manual", "Manual", "Automatic", "Manual",
        "Automatic", "Manual", "Automatic", "Manual", "Automatic"],
"Engine_cc":[  2500, 1800, 1500, 1200, 1500,
        1800, 1500, 1200, 1500, 1500,
        2000, 2800, 1500, 1200, 1500,
        1200, 2000, 2500, 1500, 1500,
        1600, 1200, 1500, 1800, 1500,
        1800, 1200, 1500, 2500, 1200,
        1500, 1500, 1500, 2000, 2800,
        1200, 1200, 1500, 1200, 2500,
        2000, 1500, 1600, 1800, 1200,
        2500, 1500, 1500, 1200, 1500],
"Owner_Count":[   1, 2, 1, 3, 1,
        2, 1, 2, 3, 1,
        2, 1, 2, 1, 2,
        1, 3, 2, 1, 2,
        1, 3, 2, 1, 2,
        1, 2, 1, 3, 2,
        1, 2, 3, 1, 2,
        1, 2, 1, 2, 3,
        1, 2, 1, 3, 2,
        1, 2, 3, 1, 2]}
df=pd.DataFrame(data)
df

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
0,1001,Toyota,Camry,2020,25000,45000,Petrol,Automatic,2500,1
1,1002,Honda,Civic,2019,22000,52000,Diesel,Manual,1800,2
2,1003,Hyundai,Creta,2021,24000,30000,Petrol,Automatic,1500,1
3,1004,Maruti,Swift,2018,12000,60000,Petrol,Manual,1200,3
4,1005,Tata,Nexon,2022,18000,25000,Diesel,Manual,1500,1
5,1006,Toyota,Corolla,2020,27000,40000,Petrol,Automatic,1800,2
6,1007,Honda,City,2019,21000,48000,Diesel,Manual,1500,1
7,1008,Hyundai,i20,2021,16000,35000,Petrol,Manual,1200,2
8,1009,Ford,EcoSport,2018,15000,70000,Diesel,Manual,1500,3
9,1010,Kia,Seltos,2022,23000,28000,Petrol,Automatic,1500,1
10,1011,Tata,Harrier,2020,28000,32000,Diesel,Automatic,2000,2
11,1012,Toyota,Fortuner,2021,42000,45000,Diesel,Automatic,2800,1
12,1013,Honda,Amaze,2019,17000,50000,Petrol,Manual,1500,2
13,1014,Maruti,Baleno,2022,14000,22000,Petrol,Manual,1200,1
14,1015,Hyundai,Venue,2020,19000,38000,Diesel,Automatic,1500,2
15,1016,Kia,Sonet,2021,21000,29000,Petrol,Automatic,1200,1
16,1017,Ford,Endeavour,2018,35000,65000,Diesel,Manual,2000,3
17,1018,Toyota,Innova,2022,30000,41000,Diesel,Automatic,2500,2
18,1019,Tata,Nexon,2020,20000,33000,Petrol,Manual,1500,1
19,1020,Honda,City,2019,19000,55000,Diesel,Manual,1500,2
20,1021,Hyundai,Verna,2021,18000,27000,Petrol,Automatic,1600,1
21,1022,Maruti,Swift,2018,11000,62000,Petrol,Manual,1200,3
22,1023,Kia,Carens,2022,25000,24000,Petrol,Automatic,1500,2
23,1024,Toyota,Corolla,2020,26000,36000,Diesel,Automatic,1800,1
24,1025,Ford,Aspire,2019,13000,68000,Petrol,Manual,1500,2
25,1026,Honda,Civic,2021,23000,42000,Petrol,Automatic,1800,1
26,1027,Tata,Punch,2022,10000,31000,Petrol,Manual,1200,2
27,1028,Hyundai,Creta,2020,22000,39000,Diesel,Automatic,1500,1
28,1029,Toyota,Camry,2019,29000,28000,Petrol,Automatic,2500,3
29,1030,Maruti,Baleno,2021,15000,46000,Petrol,Manual,1200,2
30,1031,Kia,Seltos,2022,24000,26000,Diesel,Automatic,1500,1
31,1032,Honda,Amaze,2018,16000,53000,Petrol,Manual,1500,2
32,1033,Ford,EcoSport,2020,14000,72000,Diesel,Manual,1500,3
33,1034,Tata,Harrier,2021,27000,34000,Diesel,Automatic,2000,1
34,1035,Toyota,Fortuner,2019,40000,44000,Petrol,Automatic,2800,2
35,1036,Hyundai,i20,2022,17000,37000,Petrol,Manual,1200,1
36,1037,Maruti,Swift,2020,12500,58000,Diesel,Manual,1200,2
37,1038,Honda,City,2018,20000,49000,Petrol,Automatic,1500,1
38,1039,Kia,Sonet,2021,21500,23000,Petrol,Manual,1200,2
39,1040,Toyota,Innova,2022,31000,35000,Diesel,Automatic,2500,3
40,1041,Ford,Endeavour,2019,33000,61000,Diesel,Automatic,2000,1
41,1042,Tata,Nexon,2020,19000,30000,Petrol,Manual,1500,2
42,1043,Hyundai,Verna,2021,17500,32000,Petrol,Manual,1600,1
43,1044,Honda,Civic,2018,22500,47000,Diesel,Automatic,1800,3
44,1045,Maruti,Baleno,2022,13500,54000,Petrol,Manual,1200,2
45,1046,Toyota,Camry,2020,30000,29000,Diesel,Automatic,2500,1
46,1047,Kia,Carens,2019,24500,25000,Petrol,Manual,1500,2
47,1048,Ford,Aspire,2021,14500,66000,Diesel,Automatic,1500,3
48,1049,Tata,Punch,2022,15500,43000,Petrol,Manual,1200,1
49,1050,Honda,Amaze,2018,18500,51000,Petrol,Automatic,1500,2

In [ ]:
#this line of code give number of rows and number of columns
df.shape

(50, 10)

In [ ]:
# loc is used to find a particular row and column in a pandas dataframe
df.loc[2,"Price"]=np.nan
df.loc[9,"Price"]=np.nan
df.loc[19,"Mileage"]=np.nan
df.loc[29,"Mileage"]=np.nan
df.loc[39,"Fuel_Type"]=np.nan
df.loc[44,"Fuel_Type"]=np.nan

In [ ]:
df.isnull().sum()

Car_ID          0
Brand           0
Model           0
Year            0
Price           2
Mileage         2
Fuel_Type       2
Transmission    0
Engine_cc       0
Owner_Count     0
dtype: int64

In [ ]:
'''concat is use to sum to string syntax concat(a,b),
iloc is to select position using position index syntax
iloc[row index number,column index number]
ignore_index=True this tells pandas to forget the old
index number 5,10,20 and create a fresh index from 0'''
df=pd.concat([df,df.iloc[[5,10,20]]], ignore_index=True)

In [ ]:
# adding inconsistent text vaues and numerical values in dataset
df.loc[0,'Brand']='toyota'
df.loc[1,'Brand']='TOYOTA'
df.loc[3,'Brand']='Toyta'

df.loc[4,'Fuel_Type']='petrol'
df.loc[7,'Fuel_Type']='PETROL'
df.loc[11,'Fuel_Type']='diesel'

df.loc[34,'Transmission']='automatic'
df.loc[27,'Transmission']='MANUAL'

df.loc[10,'Price']=-5000
df.loc[11,'Mileage']=-10000
df.loc[12,'Engine_cc']=-1500

# add invalid year values
df.loc[14,'Year']=1890
df.loc[15,'Year']=2035

In [ ]:
''''to_csv() means:Save this DataFrame as a CSV file.
 "automotive_dataset_dirty.csv" this name we are giving to the file
 index=False Our DataFrame has an index:We don't need to save those
 index numbers as an extra column in our CSV.'''
df.to_csv('automotive_dataset_dirty.csv', index=False)
print("Dirty automotive dataset created successfully!")

Dirty automotive dataset created successfully!

In [ ]:
df.shape

(53, 10)

In [ ]:
print('Number of Rows : ',len(df))
print('Number of Columns : ',len(df.columns))
print('\nDuplicate values : ',df.duplicated().sum())
print('\nMissing values : ')
print(df.isnull().sum())

Number of Rows :  53
Number of Columns :  10

Duplicate values :  2

Missing values :
Car_ID          0
Brand           0
Model           0
Year            0
Price           2
Mileage         2
Fuel_Type       2
Transmission    0
Engine_cc       0
Owner_Count     0
dtype: int64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df['Car_ID'].duplicated().sum()

np.int64(1)

In [ ]:
df=df.drop_duplicates(subset='Car_ID')

In [ ]:
df['Price']=df['Price'].fillna(df['Price'].median())
df['Mileage']=df['Mileage'].fillna(df['Mileage'].median())
df['Fuel_Type']=df['Fuel_Type'].fillna(df['Fuel_Type'].mode()[0])

In [ ]:
df.isnull().sum()

Car_ID          0
Brand           0
Model           0
Year            0
Price           0
Mileage         0
Fuel_Type       0
Transmission    0
Engine_cc       0
Owner_Count     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
0,1001,toyota,Camry,2020,25000.0,45000.0,Petrol,Automatic,2500,1
1,1002,TOYOTA,Civic,2019,22000.0,52000.0,Diesel,Manual,1800,2
2,1003,Hyundai,Creta,2021,19500.0,30000.0,Petrol,Automatic,1500,1
3,1004,Toyta,Swift,2018,12000.0,60000.0,Petrol,Manual,1200,3
4,1005,Tata,Nexon,2022,18000.0,25000.0,petrol,Manual,1500,1
5,1006,Toyota,Corolla,2020,27000.0,40000.0,Petrol,Automatic,1800,2
6,1007,Honda,City,2019,21000.0,48000.0,Diesel,Manual,1500,1
7,1008,Hyundai,i20,2021,16000.0,35000.0,PETROL,Manual,1200,2
8,1009,Ford,EcoSport,2018,15000.0,70000.0,Diesel,Manual,1500,3
9,1010,Kia,Seltos,2022,19500.0,28000.0,Petrol,Automatic,1500,1
10,1011,Tata,Harrier,2020,-5000.0,32000.0,Diesel,Automatic,2000,2
11,1012,Toyota,Fortuner,2021,42000.0,-10000.0,diesel,Automatic,2800,1
12,1013,Honda,Amaze,2019,17000.0,50000.0,Petrol,Manual,-1500,2
13,1014,Maruti,Baleno,2022,14000.0,22000.0,Petrol,Manual,1200,1
14,1015,Hyundai,Venue,1890,19000.0,38000.0,Diesel,Automatic,1500,2
15,1016,Kia,Sonet,2035,21000.0,29000.0,Petrol,Automatic,1200,1
16,1017,Ford,Endeavour,2018,35000.0,65000.0,Diesel,Manual,2000,3
17,1018,Toyota,Innova,2022,30000.0,41000.0,Diesel,Automatic,2500,2
18,1019,Tata,Nexon,2020,20000.0,33000.0,Petrol,Manual,1500,1
19,1020,Honda,City,2019,19000.0,38500.0,Diesel,Manual,1500,2
20,1021,Hyundai,Verna,2021,18000.0,27000.0,Petrol,Automatic,1600,1
21,1022,Maruti,Swift,2018,11000.0,62000.0,Petrol,Manual,1200,3
22,1023,Kia,Carens,2022,25000.0,24000.0,Petrol,Automatic,1500,2
23,1024,Toyota,Corolla,2020,26000.0,36000.0,Diesel,Automatic,1800,1
24,1025,Ford,Aspire,2019,13000.0,68000.0,Petrol,Manual,1500,2
25,1026,Honda,Civic,2021,23000.0,42000.0,Petrol,Automatic,1800,1
26,1027,Tata,Punch,2022,10000.0,31000.0,Petrol,Manual,1200,2
27,1028,Hyundai,Creta,2020,22000.0,39000.0,Diesel,MANUAL,1500,1
28,1029,Toyota,Camry,2019,29000.0,28000.0,Petrol,Automatic,2500,3
29,1030,Maruti,Baleno,2021,15000.0,38500.0,Petrol,Manual,1200,2
30,1031,Kia,Seltos,2022,24000.0,26000.0,Diesel,Automatic,1500,1
31,1032,Honda,Amaze,2018,16000.0,53000.0,Petrol,Manual,1500,2
32,1033,Ford,EcoSport,2020,14000.0,72000.0,Diesel,Manual,1500,3
33,1034,Tata,Harrier,2021,27000.0,34000.0,Diesel,Automatic,2000,1
34,1035,Toyota,Fortuner,2019,40000.0,44000.0,Petrol,automatic,2800,2
35,1036,Hyundai,i20,2022,17000.0,37000.0,Petrol,Manual,1200,1
36,1037,Maruti,Swift,2020,12500.0,58000.0,Diesel,Manual,1200,2
37,1038,Honda,City,2018,20000.0,49000.0,Petrol,Automatic,1500,1
38,1039,Kia,Sonet,2021,21500.0,23000.0,Petrol,Manual,1200,2
39,1040,Toyota,Innova,2022,31000.0,35000.0,Petrol,Automatic,2500,3
40,1041,Ford,Endeavour,2019,33000.0,61000.0,Diesel,Automatic,2000,1
41,1042,Tata,Nexon,2020,19000.0,30000.0,Petrol,Manual,1500,2
42,1043,Hyundai,Verna,2021,17500.0,32000.0,Petrol,Manual,1600,1
43,1044,Honda,Civic,2018,22500.0,47000.0,Diesel,Automatic,1800,3
44,1045,Maruti,Baleno,2022,13500.0,54000.0,Petrol,Manual,1200,2
45,1046,Toyota,Camry,2020,30000.0,29000.0,Diesel,Automatic,2500,1
46,1047,Kia,Carens,2019,24500.0,25000.0,Petrol,Manual,1500,2
47,1048,Ford,Aspire,2021,14500.0,66000.0,Diesel,Automatic,1500,3
48,1049,Tata,Punch,2022,15500.0,43000.0,Petrol,Manual,1200,1
49,1050,Honda,Amaze,2018,18500.0,51000.0,Petrol,Automatic,1500,2

In [ ]:
df[(df['Year']<2000) |(df['Year']>2026)]

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
14,1015,Hyundai,Venue,1890,19000.0,38000.0,Diesel,Automatic,1500,2
15,1016,Kia,Sonet,2035,21000.0,29000.0,Petrol,Automatic,1200,1

In [ ]:
df.loc[(df['Year']<1900)|(df['Year']>2026),'Year']=np.nan

In [ ]:
df['Year']=df['Year'].fillna(df['Year'].median())

In [ ]:
df[df['Price']<0]

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
10,1011,Tata,Harrier,2020.0,-5000.0,32000.0,Diesel,Automatic,2000,2

In [ ]:
df.loc[df['Price']<0,'Price']=np.nan

In [ ]:
df['Price']=df['Price'].fillna(df['Price'].median())

In [ ]:
df[df['Mileage']<0]

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
11,1012,Toyota,Fortuner,2021.0,42000.0,-10000.0,diesel,Automatic,2800,1

In [ ]:
df.loc[df['Mileage']<0,'Mileage']=np.nan

In [ ]:
df['Mileage']=df['Mileage'].fillna(df['Mileage']).median()

In [ ]:
df[df['Engine_cc']<0]

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
12,1013,Honda,Amaze,2019.0,17000.0,38500.0,Petrol,Manual,-1500,2

In [ ]:
df.loc[df['Engine_cc']<0,'Engine_cc']=np.nan

In [ ]:
df['Engine_cc'] = df['Engine_cc'].fillna(df['Engine_cc'].median())

In [ ]:
df

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
0,1001,toyota,Camry,2020.0,25000.0,38500.0,Petrol,Automatic,2500.0,1
1,1002,TOYOTA,Civic,2019.0,22000.0,38500.0,Diesel,Manual,1800.0,2
2,1003,Hyundai,Creta,2021.0,19500.0,38500.0,Petrol,Automatic,1500.0,1
3,1004,Toyta,Swift,2018.0,12000.0,38500.0,Petrol,Manual,1200.0,3
4,1005,Tata,Nexon,2022.0,18000.0,38500.0,petrol,Manual,1500.0,1
5,1006,Toyota,Corolla,2020.0,27000.0,38500.0,Petrol,Automatic,1800.0,2
6,1007,Honda,City,2019.0,21000.0,38500.0,Diesel,Manual,1500.0,1
7,1008,Hyundai,i20,2021.0,16000.0,38500.0,PETROL,Manual,1200.0,2
8,1009,Ford,EcoSport,2018.0,15000.0,38500.0,Diesel,Manual,1500.0,3
9,1010,Kia,Seltos,2022.0,19500.0,38500.0,Petrol,Automatic,1500.0,1
10,1011,Tata,Harrier,2020.0,19500.0,38500.0,Diesel,Automatic,2000.0,2
11,1012,Toyota,Fortuner,2021.0,42000.0,38500.0,diesel,Automatic,2800.0,1
12,1013,Honda,Amaze,2019.0,17000.0,38500.0,Petrol,Manual,1500.0,2
13,1014,Maruti,Baleno,2022.0,14000.0,38500.0,Petrol,Manual,1200.0,1
14,1015,Hyundai,Venue,2020.0,19000.0,38500.0,Diesel,Automatic,1500.0,2
15,1016,Kia,Sonet,2020.0,21000.0,38500.0,Petrol,Automatic,1200.0,1
16,1017,Ford,Endeavour,2018.0,35000.0,38500.0,Diesel,Manual,2000.0,3
17,1018,Toyota,Innova,2022.0,30000.0,38500.0,Diesel,Automatic,2500.0,2
18,1019,Tata,Nexon,2020.0,20000.0,38500.0,Petrol,Manual,1500.0,1
19,1020,Honda,City,2019.0,19000.0,38500.0,Diesel,Manual,1500.0,2
20,1021,Hyundai,Verna,2021.0,18000.0,38500.0,Petrol,Automatic,1600.0,1
21,1022,Maruti,Swift,2018.0,11000.0,38500.0,Petrol,Manual,1200.0,3
22,1023,Kia,Carens,2022.0,25000.0,38500.0,Petrol,Automatic,1500.0,2
23,1024,Toyota,Corolla,2020.0,26000.0,38500.0,Diesel,Automatic,1800.0,1
24,1025,Ford,Aspire,2019.0,13000.0,38500.0,Petrol,Manual,1500.0,2
25,1026,Honda,Civic,2021.0,23000.0,38500.0,Petrol,Automatic,1800.0,1
26,1027,Tata,Punch,2022.0,10000.0,38500.0,Petrol,Manual,1200.0,2
27,1028,Hyundai,Creta,2020.0,22000.0,38500.0,Diesel,MANUAL,1500.0,1
28,1029,Toyota,Camry,2019.0,29000.0,38500.0,Petrol,Automatic,2500.0,3
29,1030,Maruti,Baleno,2021.0,15000.0,38500.0,Petrol,Manual,1200.0,2
30,1031,Kia,Seltos,2022.0,24000.0,38500.0,Diesel,Automatic,1500.0,1
31,1032,Honda,Amaze,2018.0,16000.0,38500.0,Petrol,Manual,1500.0,2
32,1033,Ford,EcoSport,2020.0,14000.0,38500.0,Diesel,Manual,1500.0,3
33,1034,Tata,Harrier,2021.0,27000.0,38500.0,Diesel,Automatic,2000.0,1
34,1035,Toyota,Fortuner,2019.0,40000.0,38500.0,Petrol,automatic,2800.0,2
35,1036,Hyundai,i20,2022.0,17000.0,38500.0,Petrol,Manual,1200.0,1
36,1037,Maruti,Swift,2020.0,12500.0,38500.0,Diesel,Manual,1200.0,2
37,1038,Honda,City,2018.0,20000.0,38500.0,Petrol,Automatic,1500.0,1
38,1039,Kia,Sonet,2021.0,21500.0,38500.0,Petrol,Manual,1200.0,2
39,1040,Toyota,Innova,2022.0,31000.0,38500.0,Petrol,Automatic,2500.0,3
40,1041,Ford,Endeavour,2019.0,33000.0,38500.0,Diesel,Automatic,2000.0,1
41,1042,Tata,Nexon,2020.0,19000.0,38500.0,Petrol,Manual,1500.0,2
42,1043,Hyundai,Verna,2021.0,17500.0,38500.0,Petrol,Manual,1600.0,1
43,1044,Honda,Civic,2018.0,22500.0,38500.0,Diesel,Automatic,1800.0,3
44,1045,Maruti,Baleno,2022.0,13500.0,38500.0,Petrol,Manual,1200.0,2
45,1046,Toyota,Camry,2020.0,30000.0,38500.0,Diesel,Automatic,2500.0,1
46,1047,Kia,Carens,2019.0,24500.0,38500.0,Petrol,Manual,1500.0,2
47,1048,Ford,Aspire,2021.0,14500.0,38500.0,Diesel,Automatic,1500.0,3
48,1049,Tata,Punch,2022.0,15500.0,38500.0,Petrol,Manual,1200.0,1
49,1050,Honda,Amaze,2018.0,18500.0,38500.0,Petrol,Automatic,1500.0,2

In [ ]:
df["Brand"].unique()

array(['toyota', 'TOYOTA', 'Hyundai', 'Toyta', 'Tata', 'Toyota', 'Honda',
       'Ford', 'Kia', 'Maruti'], dtype=object)

In [ ]:
df['Brand']=df['Brand'].str.strip().str.title()

In [ ]:
df['Brand']=df['Brand'].replace('Toyta','Toyota')

In [ ]:
df['Model'].unique()

array(['Camry', 'Civic', 'Creta', 'Swift', 'Nexon', 'Corolla', 'City',
       'i20', 'EcoSport', 'Seltos', 'Harrier', 'Fortuner', 'Amaze',
       'Baleno', 'Venue', 'Sonet', 'Endeavour', 'Innova', 'Verna',
       'Carens', 'Aspire', 'Punch'], dtype=object)

In [ ]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'petrol', 'PETROL', 'diesel'], dtype=object)

In [ ]:
df['Fuel_Type']=df['Fuel_Type'].str.strip().str.title()

In [ ]:
df['Transmission'].unique()

array(['Automatic', 'Manual', 'MANUAL', 'automatic'], dtype=object)

In [ ]:
df['Transmission'] = df['Transmission'].str.strip().str.title()

In [ ]:
df.isnull().sum()

Car_ID          0
Brand           0
Model           0
Year            0
Price           0
Mileage         0
Fuel_Type       0
Transmission    0
Engine_cc       0
Owner_Count     0
dtype: int64

,Car_ID,Brand,Model,Year,Price,Mileage,Fuel_Type,Transmission,Engine_cc,Owner_Count
0,1001,Toyota,Camry,2020.0,25000.0,38500.0,Petrol,Automatic,2500.0,1
1,1002,Toyota,Civic,2019.0,22000.0,38500.0,Diesel,Manual,1800.0,2
2,1003,Hyundai,Creta,2021.0,19500.0,38500.0,Petrol,Automatic,1500.0,1
3,1004,Toyota,Swift,2018.0,12000.0,38500.0,Petrol,Manual,1200.0,3
4,1005,Tata,Nexon,2022.0,18000.0,38500.0,Petrol,Manual,1500.0,1
5,1006,Toyota,Corolla,2020.0,27000.0,38500.0,Petrol,Automatic,1800.0,2
6,1007,Honda,City,2019.0,21000.0,38500.0,Diesel,Manual,1500.0,1
7,1008,Hyundai,i20,2021.0,16000.0,38500.0,Petrol,Manual,1200.0,2
8,1009,Ford,EcoSport,2018.0,15000.0,38500.0,Diesel,Manual,1500.0,3
9,1010,Kia,Seltos,2022.0,19500.0,38500.0,Petrol,Automatic,1500.0,1
10,1011,Tata,Harrier,2020.0,19500.0,38500.0,Diesel,Automatic,2000.0,2
11,1012,Toyota,Fortuner,2021.0,42000.0,38500.0,Diesel,Automatic,2800.0,1
12,1013,Honda,Amaze,2019.0,17000.0,38500.0,Petrol,Manual,1500.0,2
13,1014,Maruti,Baleno,2022.0,14000.0,38500.0,Petrol,Manual,1200.0,1
14,1015,Hyundai,Venue,2020.0,19000.0,38500.0,Diesel,Automatic,1500.0,2
15,1016,Kia,Sonet,2020.0,21000.0,38500.0,Petrol,Automatic,1200.0,1
16,1017,Ford,Endeavour,2018.0,35000.0,38500.0,Diesel,Manual,2000.0,3
17,1018,Toyota,Innova,2022.0,30000.0,38500.0,Diesel,Automatic,2500.0,2
18,1019,Tata,Nexon,2020.0,20000.0,38500.0,Petrol,Manual,1500.0,1
19,1020,Honda,City,2019.0,19000.0,38500.0,Diesel,Manual,1500.0,2
20,1021,Hyundai,Verna,2021.0,18000.0,38500.0,Petrol,Automatic,1600.0,1
21,1022,Maruti,Swift,2018.0,11000.0,38500.0,Petrol,Manual,1200.0,3
22,1023,Kia,Carens,2022.0,25000.0,38500.0,Petrol,Automatic,1500.0,2
23,1024,Toyota,Corolla,2020.0,26000.0,38500.0,Diesel,Automatic,1800.0,1
24,1025,Ford,Aspire,2019.0,13000.0,38500.0,Petrol,Manual,1500.0,2
25,1026,Honda,Civic,2021.0,23000.0,38500.0,Petrol,Automatic,1800.0,1
26,1027,Tata,Punch,2022.0,10000.0,38500.0,Petrol,Manual,1200.0,2
27,1028,Hyundai,Creta,2020.0,22000.0,38500.0,Diesel,Manual,1500.0,1
28,1029,Toyota,Camry,2019.0,29000.0,38500.0,Petrol,Automatic,2500.0,3
29,1030,Maruti,Baleno,2021.0,15000.0,38500.0,Petrol,Manual,1200.0,2
30,1031,Kia,Seltos,2022.0,24000.0,38500.0,Diesel,Automatic,1500.0,1
31,1032,Honda,Amaze,2018.0,16000.0,38500.0,Petrol,Manual,1500.0,2
32,1033,Ford,EcoSport,2020.0,14000.0,38500.0,Diesel,Manual,1500.0,3
33,1034,Tata,Harrier,2021.0,27000.0,38500.0,Diesel,Automatic,2000.0,1
34,1035,Toyota,Fortuner,2019.0,40000.0,38500.0,Petrol,Automatic,2800.0,2
35,1036,Hyundai,i20,2022.0,17000.0,38500.0,Petrol,Manual,1200.0,1
36,1037,Maruti,Swift,2020.0,12500.0,38500.0,Diesel,Manual,1200.0,2
37,1038,Honda,City,2018.0,20000.0,38500.0,Petrol,Automatic,1500.0,1
38,1039,Kia,Sonet,2021.0,21500.0,38500.0,Petrol,Manual,1200.0,2
39,1040,Toyota,Innova,2022.0,31000.0,38500.0,Petrol,Automatic,2500.0,3
40,1041,Ford,Endeavour,2019.0,33000.0,38500.0,Diesel,Automatic,2000.0,1
41,1042,Tata,Nexon,2020.0,19000.0,38500.0,Petrol,Manual,1500.0,2
42,1043,Hyundai,Verna,2021.0,17500.0,38500.0,Petrol,Manual,1600.0,1
43,1044,Honda,Civic,2018.0,22500.0,38500.0,Diesel,Automatic,1800.0,3
44,1045,Maruti,Baleno,2022.0,13500.0,38500.0,Petrol,Manual,1200.0,2
45,1046,Toyota,Camry,2020.0,30000.0,38500.0,Diesel,Automatic,2500.0,1
46,1047,Kia,Carens,2019.0,24500.0,38500.0,Petrol,Manual,1500.0,2
47,1048,Ford,Aspire,2021.0,14500.0,38500.0,Diesel,Automatic,1500.0,3
48,1049,Tata,Punch,2022.0,15500.0,38500.0,Petrol,Manual,1200.0,1
49,1050,Honda,Amaze,2018.0,18500.0,38500.0,Petrol,Automatic,1500.0,2